# Site settings
title: Robert H. Lampe
baseurl: "/"
url: "https://rhlampe.github.io"
google_analytics: "G-RWCX6FJ6JG" 

# Author
author:
  name: Robert H. Lampe
  name2: Rob H. Lampe
  desc: Postdoctoral Fellow 
  desc2: <a href="https://www2.whoi.edu/site/saito-lab/">Saito Lab</a>
  desc3: <a href="https://www.whoi.edu/">Woods Hole Oceanographic Institution</a>
  email: robert.lampe@whoi.edu
  selfie: assets/img/profile.jpg

# social
social:
  email: 
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: 
  google_plus:
  instagram:
  keybase:
  linkedin: 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:  
  vimeo:
  wordpress:
  youtube:
  default_txt:  

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
